version: "3.7"
name: groceries

volumes:
  groceries-postgres-dev:

services:
  postgres:
    image: postgres:17.2
    restart: always
    volumes:
      - groceries-postgres-dev:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: groceries
      POSTGRES_PASSWORD: groceries
      POSTGRES_DB: groceries
    ports:
      - 5432:5432

